language: haskell

before_install:
  - mkdir -p ~/.local/bin/stack
  - export PATH=~/.local/bin/stack:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v/stack-1.0.4.3-linux-x86_64.tar.gz | tar -xzf- -C ~/.local/bin/stack --strip-components=1
  - chmod a+x ~/.local/bin/stack/stack

cache:
  directories:
    - $HOME/.stack/

install:
  - stack setup --no-terminal
  - stack build --no-terminal

script:
  - stack build --no-terminal

sudo: false
